project:
  name: quickstart-compliance-uk-official
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
    - eu-west-2
tests:
  compl-uk-official:
    parameters:
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      CisAlertingEmail: foo@example.com
      DBPassword: $[taskcat_genpass_28]
    regions:
      - eu-west-2
    template: templates/main.template
