project:
  name: quickstart-microsoft-sql
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
  - eu-west-2
  s3_bucket: ''
tests:
  ec2-li-2016:
    parameters:
      DBPassword: $[taskcat_genpass_28]
      CisAlertingEmail: distlist@example.org
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
    regions:
    - eu-west-2
    s3_bucket: ''
    template: templates/master_template.yaml
